template: Hello, %s!
defaultName: Stranger


database:
  # the name of your JDBC driver
  driverClass: org.h2.Driver

  # the username
  user: test

  # the password
  password: 12345

  # the JDBC URL
  url: jdbc:h2:mem:test_db